Repository Bootcamp-Group5/simply-unused, pull requests merged in 2021-03, with the labels that each got.

#15 Feature/mvc file structure
  .env
  .gitignore
  Public/javascript/idle-timer.js
  Public/javascript/login.js
  Public/javascript/logout.js
  Public/javascript/sign-up.js
  Public/stylesheets/style.css
  config/connection.js
  controllers/controllers/api/index.js
  controllers/controllers/api/placeholder.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  controllers/index.js
  dashboard.html
  db/schema.sql
  index.html
  login.html
  models/Product.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  server.js
  signUp.html
  utils/auth.js
  utils/helpers.js
  views/dashboard.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/placeholder.handlebars
  views/signUp.handlebars
Labels: enhancement

#16 merge develop from main.
  .env
  .gitignore
  Public/javascript/idle-timer.js
  Public/javascript/login.js
  Public/javascript/logout.js
  Public/javascript/sign-up.js
  Public/stylesheets/style.css
  README.md
  config/connection.js
  controllers/controllers/api/index.js
  controllers/controllers/api/placeholder.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  controllers/index.js
  db/schema.sql
  models/Product.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  server.js
  utils/auth.js
  utils/helpers.js
  views/dashboard.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/placeholder.handlebars
  views/signUp.handlebars
Labels: enhancement

#28 Feature/esteban api routes
  .env
  Public/javascript/login.js
  Public/javascript/logout.js
  Public/javascript/sign-up.js
  controllers/api/index.js
  controllers/api/product-routes.js
  controllers/api/user-routes.js
  controllers/controllers/api/index.js
  controllers/controllers/api/placeholder.js
  controllers/home-routes.js
  controllers/index.js
  server.js
  utils/auth.js
  views/dashboard.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/placeholder.handlebars
  views/partials/product-info.handlebars
  views/signUp.handlebars
Labels: enhancement

#29 Feature/esteban api routes
  views/dashboard.handlebars
  views/partials/product-info.handlebars
Labels: enhancement

#40 fixed the order by or sorting mechanism
  controllers/dashboard-routes.js
Labels: bug

#41 icons added back
  views/layouts/main.handlebars
Labels: bug

#50 Feature/front end js
  Public/javascript/dashboard.js
  Public/javascript/home.js
  Public/stylesheets/style.css
  views/dashboard.handlebars
  views/homepage.handlebars
  views/partials/product-info.handlebars
Labels: enhancement

#64 Feature/home added back
  public/javascript/animations.js
  public/javascript/logout.js
  views/layouts/main.handlebars
Labels: bug, documentation

#68 Feature/new routes esteban
  controllers/home-routes.js
  views/layouts/main.handlebars
Labels: documentation

#69 clear select err when user add a product
  public/javascript/home.js
Labels: bug, enhancement

#70 Feature/input err
  public/javascript/home.js
Labels: enhancement

#77 Feature/text messaging
  controllers/api/user-routes.js
  models/User.js
  public/javascript/sign-up.js
  server.js
  views/signUp.handlebars
Labels: enhancement

#78 installed json file twilio
  package-lock.json
  package.json
Labels: enhancement

#79 removed testing text script
  server.js
Labels: enhancement

#80 text messages completed
  package.json
  server.js
Labels: enhancement
